# Generated by Django 5.1.3 on 2024-12-03 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$kYdbMnSho6fhDkM4rOC0tX$dGza9+5Llz1U21xlpaAjoPq2ZT9YQc15lkXCaZisBB4=', max_length=128),
        ),
        migrations.CreateModel(
            name='CustomOutstandingToken',
            fields=[
                ('outstandingtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.outstandingtoken')),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_outstanding_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'proxy': False,
            },
            bases=('token_blacklist.outstandingtoken',),
        ),
    ]
