# Generated by Django 5.1.3 on 2024-12-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_blog_user_password_customoutstandingtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='blog_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userdp/'),
        ),
    ]
